# Generated by Django 4.2.4 on 2023-08-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='signer',
        ),
        migrations.AddField(
            model_name='signature',
            name='signer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='student_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
