# Generated by Django 4.2.4 on 2023-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_signature_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvolvedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('office_address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='required_signatures_range',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='involved_parties',
            field=models.ManyToManyField(related_name='entities', to='api.involvedparty'),
        ),
    ]
