# Generated by Django 4.2.4 on 2023-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_involvedparty_petition_required_signatures_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, default='bot_icon.png', null=True, upload_to='images/'),
        ),
    ]
