# Generated by Django 4.2.4 on 2023-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_petition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
